### ISSUE TITLE
Need an option to turn off curl verbose logging

### ISSUE THREAD

**Issue by 9rj** [escopecz/mautic-form-submit#11]
I see that you're using the verbose option when making curl requests:-
`curl_setopt($ch, CURLOPT_VERBOSE, 1);`
If I use this in production it's going to write a lot of unnecessary data to my error logs. I don't want to edit your code directly since I'm installing it via composer. Could you consider turning this option off? 

If there's a better way of dealing with this then I'd be glad to hear it.

**Comment by escopecz** [comment]
Good idea. It would be great to create a new DTO object for configuration and pass it to the Mautic object. Something like:

```
$config = Config();
$config->setCurlVerbose(false);
$mautic = new Mautic('https://mymautic.com', $config);
```

And then use this in the Form class like:
```
curl_setopt($ch, CURLOPT_VERBOSE, $this->mautic->getConfig()->getCurlVerbose());
```

If you'd have time to implement this that would speed it up.

**Comment by escopecz** [comment]
Implemented in https://github.com/escopecz/mautic-form-submit/pull/12
