### ISSUE TITLE
If Refer contains UTM & FB tracking pixel - form not submit

### ISSUE THREAD

**Issue by zaharovrd** [escopecz/mautic-form-submit#16]
Example,
if  send form directly - all ok.
if add utm-tag:
`https://lp.everest-dom.com/page16934025.html?utm_source=fb_polyakov&amp;utm_medium=1 - Руководство PDF - 08.02 | 100 рег | 5к - CBO - CPA&amp;utm_campaign=6 - LaL 1% (лид-формы переселенцы)&amp;utm_content=5k_3t&amp;fbclid=PAAaaOOSN22K3x6eFXnwvDDVfZfOZvBn7_TFRtYCXE9PqEiYc1mUH3-VL9jUg`

form not send...

**Comment by escopecz** [comment]
Why do you have `&amp;` instead of just `&`?

**Comment by zaharovrd** [comment]
it just got replaced on copy

**Comment by escopecz** [comment]
Any error in the Mautic log?

**Comment by zaharovrd** [comment]
only
[2021-02-11 09:11:29] mautic.WARNING: PHP Warning - Invalid argument supplied for foreach() - in file /home/master/m.everest-dom.com/app/bundles/PageBundle/Model/PageModel.php - at line 1189 {"query":"utm_campaign=yaroslavl_all&utm_medium=referral&utm_source=vk%D1%81_funnel"} []

**Comment by escopecz** [comment]
It could be the reason. Please report it to https://github.com/mautic/mautic. It's issue in Mautic itself.

**Comment by zaharovrd** [comment]
> It could be the reason. Please report it to https://github.com/mautic/mautic. It's issue in Mautic itself.

John, why?

if you send the same traffic to a standard mautic landing page - everything is ok.
This means that the problem is not in the mautic, but in the script

**Comment by escopecz** [comment]
It looks like it based on the Mautic PHP warning. Maybe I don't understand your use case. Can you share your code?

**Comment by zaharovrd** [comment]
No, this warning is not related to form submission in my example )

for my case - log is clean


**try add this utm tags for your form:**

`utm_source=fb_polyakov&utm_medium=1 - Руководство PDF - 08.02 | 100 рег | 5к - CBO - CPA&utm_campaign=6 - LaL 1% (лид-формы переселенцы)&utm_content=5k_3t&fbclid=PAAaaOOSN22K3x6eFXnwvDDVfZfOZvBn7_TFRtYCXE9PqEiYc1mUH3-VL9jUg`

**Comment by escopecz** [comment]
I don't understand where you are adding this. That's why I asked for a code example.

**Comment by zaharovrd** [comment]
i sent this utm's with name, email and form_id to 
m.everest-dom.com/webhook/mautic-form-submit/tilda.php as webhook

`<?php

    $email = $_REQUEST['Email']; // mauticform_input_mkregistraciaslp_email
    $name = $_REQUEST['Name']; // mauticform_input_mkregistraciaslp_name
    $phone = $_REQUEST['Phone']); // mauticform_input_mkregistraciaslp_phone
	$location = $_REQUEST['location']; // mauticform_input_mkregistraciaslp_location
	$form_id = $_REQUEST['form_id']; // mauticform_input_mkregistraciaslp_form_id
    require __DIR__.'/vendor/autoload.php';
    use Escopecz\MauticFormSubmit\Mautic;
    $mautic = new Mautic('https://m.everest-dom.com');
    $form = $mautic->getForm($form_id);
    $result = $form->submit(['email' => $email, 'phone' => $phone, 'f_name' => $name, 'location' => $location]);
    header('Location: https://m.everest-dom.com/emailconfirm');
?>`

**Comment by escopecz** [comment]
So the above script works? Where are the UTM tags?

**Comment by zaharovrd** [comment]
> I don't understand where you are adding this. That's why I asked for a code example.

I don't understand what code example to provide (

I have provided example tags so you can reproduce the problem, let's substitute them for ourselves. For example by clicking on the link:

https://johnlinhart.com/?utm_source=fb_polyakov&utm_medium=1 - Руководство PDF - 08.02 | 100 рег | 5к - CBO - CPA&utm_campaign=6 - LaL 1% (лид-формы переселенцы)&utm_content=5k_3t&fbclid=PAAaaOOSN22K3x6eFXnwvDDVfZfOZvBn7_TFRtYCXE9PqEiYc1mUH3-VL9jUg

and send form to mautic-form-submit - contact not create in mautic

**Comment by zaharovrd** [comment]
> So the above script works? Where are the UTM tags?

If i send only name & email to this script - all OK )
If i add UTM tags - sctipt not work (

**Comment by escopecz** [comment]
I'm sorry I still don't understand how you add the UTM tags. In the query parameters? Have you noticed even when you paste it into the comment then the parameters aren't part of the automated link? You have to [urlencode](https://www.php.net/manual/en/function.urlencode.php) the UTM values first.
