### ISSUE TITLE
Using the composer command broke my mautic installation

### ISSUE THREAD

**Issue by surefooted** [escopecz/mautic-form-submit#17]
I want to install this package but when I use the command it starts giving internal server error on the mautic installation.
Below is the output on running the command.

[site-name@sitename2 mautic]$ composer require escopecz/mautic-form-submit
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "robloach/component-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Using version ^1.1 for escopecz/mautic-form-submit
./composer.json has been created
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "robloach/component-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Running composer update escopecz/mautic-form-submit
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking escopecz/mautic-form-submit (1.1.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 194 removals
  - Downloading escopecz/mautic-form-submit (1.1.4)
  - Removing willdurand/oauth-server-bundle (dev-release-0.0.3 35979d2)
  - Removing willdurand/negotiation (v2.3.1)
  - Removing willdurand/jsonp-callback-validator (v1.1.0)
  - Removing voku/stop-words (2.0.1)
  - Removing voku/portable-ascii (1.4.10)
  - Removing twilio/sdk (5.42.2)
  - Removing twig/twig (v2.12.5)
  - Removing tightenco/collect (v6.18.6)
  - Removing symfony/yaml (v3.4.39)
  - Removing symfony/var-dumper (v3.4.39)
  - Removing symfony/validator (v3.4.39)
  - Removing symfony/twig-bundle (v3.4.39)
  - Removing symfony/twig-bridge (v4.0.15)
  - Removing symfony/translation (v3.4.39)
  - Removing symfony/templating (v3.4.39)
  - Removing symfony/swiftmailer-bundle (v3.3.1)
  - Removing symfony/stopwatch (v3.4.39)
  - Removing symfony/service-contracts (v2.0.1)
  - Removing symfony/security-bundle (v3.4.39)
  - Removing symfony/security-acl (v3.0.4)
  - Removing symfony/security (v3.4.39)
  - Removing symfony/routing (v3.4.39)
  - Removing symfony/property-access (v3.4.39)
  - Removing symfony/process (v3.4.39)
  - Removing symfony/polyfill-util (v1.15.0)
  - Removing symfony/polyfill-php74 (v1.15.0)
  - Removing symfony/polyfill-php73 (v1.15.0)
  - Removing symfony/polyfill-php72 (v1.15.0)
  - Removing symfony/polyfill-php70 (v1.15.0)
  - Removing symfony/polyfill-php56 (v1.15.0)
  - Removing symfony/polyfill-mbstring (v1.15.0)
  - Removing symfony/polyfill-intl-idn (v1.15.0)
  - Removing symfony/polyfill-intl-icu (v1.15.0)
  - Removing symfony/polyfill-iconv (v1.15.0)
  - Removing symfony/polyfill-ctype (v1.18.1)
  - Removing symfony/polyfill-apcu (v1.15.0)
  - Removing symfony/options-resolver (v3.4.39)
  - Removing symfony/monolog-bundle (v3.5.0)
  - Removing symfony/monolog-bridge (v3.4.39)
  - Removing symfony/mime (v5.0.7)
  - Removing symfony/intl (v3.4.26)
  - Removing symfony/inflector (v4.4.7)
  - Removing symfony/http-kernel (v3.4.39)
  - Removing symfony/http-foundation (v3.4.39)
  - Removing symfony/http-client-contracts (v2.0.1)
  - Removing symfony/http-client (v5.0.7)
  - Removing symfony/framework-bundle (v3.4.39)
  - Removing symfony/form (v3.4.39)
  - Removing symfony/finder (v3.4.39)
  - Removing symfony/filesystem (v3.4.39)
  - Removing symfony/expression-language (v3.4.39)
  - Removing symfony/event-dispatcher (v3.4.39)
  - Removing symfony/dotenv (v3.4.39)
  - Removing symfony/doctrine-bridge (v3.4.39)
  - Removing symfony/dependency-injection (v3.4.39)
  - Removing symfony/debug (v3.4.39)
  - Removing symfony/console (v3.4.39)
  - Removing symfony/config (v3.4.39)
  - Removing symfony/class-loader (v3.4.39)
  - Removing symfony/cache (v3.4.39)
  - Removing symfony/asset (v3.4.39)
  - Removing swiftmailer/swiftmailer (v6.2.3)
  - Removing studio-42/elfinder (2.1.57)
  - Removing stack/run (v1.1.0)
  - Removing stack/builder (v1.0.6)
  - Removing sparkpost/sparkpost (2.2.0)
  - Removing simshaun/recurr (v3.1.1)
  - Removing sensiolabs/security-checker (v6.0.3)
  - Removing sensio/framework-extra-bundle (v3.0.29)
  - Removing sensio/distribution-bundle (v5.0.25)
  - Removing sendgrid/sendgrid (6.2.0)
  - Removing sendgrid/php-http-client (3.10.5)
  - Removing robrichards/xmlseclibs (3.0.4)
  - Removing robloach/component-installer (0.2.3)
  - Removing ricardofiorani/guzzle-psr18-adapter (v1.0.3)
  - Removing ramsey/uuid (3.9.3)
  - Removing ralouphie/getallheaders (3.0.3)
  - Removing psr/simple-cache (1.0.1)
  - Removing psr/log (1.1.3)
  - Removing psr/http-message (1.0.1)
  - Removing psr/http-factory (1.0.1)
  - Removing psr/http-client (1.0.0)
  - Removing psr/container (1.0.0)
  - Removing psr/cache (1.0.1)
  - Removing piwik/device-detector (3.12.4)
  - Removing phpseclib/phpseclib (2.0.27)
  - Removing phpoffice/phpspreadsheet (1.15.0)
  - Removing php-http/promise (v1.0.0)
  - Removing php-http/message-factory (v1.0.2)
  - Removing php-http/message (1.8.0)
  - Removing php-http/httplug (v1.1.0)
  - Removing php-http/guzzle6-adapter (v1.1.1)
  - Removing php-http/discovery (1.7.4)
  - Removing php-amqplib/rabbitmq-bundle (v1.14.4)
  - Removing php-amqplib/php-amqplib (v2.11.1)
  - Removing pda/pheanstalk (v4.0.1)
  - Removing paragonie/random_compat (v2.0.18)
  - Removing oneup/uploader-bundle (2.2.0)
  - Removing ocramius/proxy-manager (2.2.3)
  - Removing ocramius/package-versions (1.4.2)
  - Removing noxlogic/ratelimit-bundle (1.15.1)
  - Removing myclabs/php-enum (1.7.7)
  - Removing mustangostang/spyc (0.6.3)
  - Removing mtdowling/jmespath.php (2.5.0)
  - Removing mrclay/minify (2.2.0)
  - Removing monolog/monolog (1.25.3)
  - Removing misd/phone-number-bundle (v1.3.2)
  - Removing maxmind/web-service-common (v0.6.0)
  - Removing maxmind-db/reader (v1.6.0)
  - Removing markbaker/matrix (2.0.0)
  - Removing markbaker/complex (2.0.0)
  - Removing malkusch/lock (v1.4)
  - Removing maennchen/zipstream-php (2.1.0)
  - Removing lightsaml/symfony-bridge (1.3.0)
  - Removing lightsaml/sp-bundle (1.2.1)
  - Removing lightsaml/lightsaml (1.4.1)
  - Removing leezy/pheanstalk-bundle (4.0.0)
  - Removing league/flysystem-cached-adapter (1.0.9)
  - Removing league/flysystem (1.0.66)
  - Removing laminas/laminas-zendframework-bridge (1.0.3)
  - Removing laminas/laminas-eventmanager (3.2.1)
  - Removing laminas/laminas-code (3.4.1)
  - Removing kriswallsmith/assetic (v1.4.0)
  - Removing knplabs/knp-menu-bundle (v2.3.0)
  - Removing knplabs/knp-menu (2.6.0)
  - Removing knplabs/gaufrette (v0.9.0)
  - Removing kamermans/guzzle-oauth2-subscriber (v1.0.6)
  - Removing joomla/uri (1.2.0)
  - Removing joomla/string (1.4.3)
  - Removing joomla/http (1.3.3)
  - Removing joomla/filter (1.3.5)
  - Removing jms/serializer-bundle (3.5.0)
  - Removing jms/serializer (3.6.0)
  - Removing jms/metadata (2.1.0)
  - Removing jdorn/sql-formatter (v1.2.17)
  - Removing jbroadway/urlify (1.2.0-stable)
  - Removing ip2location/ip2location-php (7.2.5)
  - Removing intervention/image (2.5.1)
  - Removing hoa/zformat (1.17.01.10)
  - Removing hoa/visitor (2.17.01.16)
  - Removing hoa/ustring (4.17.01.16)
  - Removing hoa/stream (1.17.02.21)
  - Removing hoa/regex (1.17.01.13)
  - Removing hoa/protocol (1.17.01.14)
  - Removing hoa/math (1.17.05.16)
  - Removing hoa/iterator (2.17.01.10)
  - Removing hoa/file (1.17.07.11)
  - Removing hoa/exception (1.17.01.16)
  - Removing hoa/event (1.17.01.13)
  - Removing hoa/consistency (1.17.05.02)
  - Removing hoa/compiler (3.17.08.08)
  - Removing helios-ag/fm-elfinder-bundle (9.3.2)
  - Removing guzzlehttp/psr7 (1.6.1)
  - Removing guzzlehttp/promises (v1.3.1)
  - Removing guzzlehttp/oauth-subscriber (0.3.0)
  - Removing guzzlehttp/guzzle (6.5.2)
  - Removing giggsey/locale (1.8)
  - Removing giggsey/libphonenumber-for-php (8.12.1)
  - Removing geoip2/geoip2 (v2.10.0)
  - Removing gaufrette/extras (v0.1.0)
  - Removing gaufrette/aws-s3-adapter (v0.4.0)
  - Removing friendsofsymfony/rest-bundle (2.6.0)
  - Removing friendsofsymfony/oauth2-php (1.3.0)
  - Removing friendsofsymfony/oauth-server-bundle (1.6.2)
  - Removing egulias/email-validator (2.1.17)
  - Removing egeloen/ordered-form-bundle (3.0.0)
  - Removing egeloen/ordered-form (3.0.0)
  - Removing doctrine/reflection (1.2.1)
  - Removing doctrine/persistence (1.3.7)
  - Removing doctrine/orm (v2.7.0)
  - Removing doctrine/migrations (2.2.1)
  - Removing doctrine/lexer (1.2.0)
  - Removing doctrine/instantiator (1.3.1)
  - Removing doctrine/inflector (1.3.1)
  - Removing doctrine/event-manager (1.1.0)
  - Removing doctrine/doctrine-migrations-bundle (2.1.2)
  - Removing doctrine/doctrine-fixtures-bundle (3.3.1)
  - Removing doctrine/doctrine-cache-bundle (1.4.0)
  - Removing doctrine/doctrine-bundle (1.12.13)
  - Removing doctrine/dbal (v2.10.1)
  - Removing doctrine/data-fixtures (1.4.2)
  - Removing doctrine/common (2.12.0)
  - Removing doctrine/collections (1.6.4)
  - Removing doctrine/cache (1.10.0)
  - Removing doctrine/annotations (v1.8.0)
  - Removing debril/rss-atom-bundle (v2.4.3)
  - Removing composer/ca-bundle (1.2.7)
  - Removing components/jqueryui (1.12.1)
  - Removing components/jquery (3.4.1)
  - Removing components/elfinder (3.1.3)
  - Removing clue/stream-filter (v1.4.1)
  - Removing barryvdh/elfinder-flysystem-driver (v0.2.1)
  - Removing bandwidth-throttle/token-bucket (2.0.0)
  - Removing aws/aws-sdk-php (3.134.6)
  - Installing escopecz/mautic-form-submit (1.1.4): Extracting archive
Generating autoload files

**Comment by escopecz** [comment]
There must be some misunderstanding. This is not a Mautic plugin. This is not something you should install into Mautic via Composer. It's a PHP library that will help you push form submissions to a Mautic instance from some 3rd party PHP app.
