### ISSUE TITLE
How to set form submission date with API? 

### ISSUE THREAD

**Issue by neversuspend** [escopecz/mautic-form-submit#19]
I have successfully submitted form through Escopecz\MauticFormSubmit\Mautic

However the event_timestamp is generated by mautic system automatically. Can I manually set it because the real form submission date may be yesterday rather than now.

**Comment by escopecz** [comment]
No, the timestamp is internal Mautic field. But you can create one more form field where you store the date you need.

**Comment by neversuspend** [comment]
Thank you for your advice.
