### ISSUE TITLE
Client IP not correctly sent to Mautic

### ISSUE THREAD

**Issue by Hemant-Mann** [escopecz/mautic-form-submit#4]
Hi
I am using this library to submit a form in mautic
I am setting the server key so that client IP is correctly fetched by this library
https://github.com/escopecz/mautic-form-submit/blob/master/src/Mautic/Contact.php#L116

```php
$data = []; // all the form data here
// Set the client IP so that library gets the ip correctly
$_SERVER['HTTP_CLIENT_IP'] = "Client IP here";

// send data to Mautic
$mktMautic = new \Escopecz\MauticFormSubmit\Mautic('http://mautic/url');
$mktForm = $mktMautic->getForm(2);
$mktForm->submit($data);
```

I have verified the request data formed by the library is correct but mautic is not taking the value in `X-Forwarded-For: Client IP` instead mautic is registering the contact with server ip (which is sending the request to mautic)

**Comment by escopecz** [comment]
The question is if this is a problem in this library or in Mautic. Could you verify that your IP is in the CURL request headers by `var_dump($request);die;` here: https://github.com/escopecz/mautic-form-submit/blob/master/src/Mautic/Form.php#L51 ?

**Comment by Hemant-Mann** [comment]
Hi @escopecz 
> The question is if this is a problem in this library or in Mautic. Could you verify that your IP is in the CURL request headers by var_dump($request);die; here: https://github.com/escopecz/mautic-form-submit/blob/master/src/Mautic/Form.php#L51 ?

**Yes correct IP is in headers**
```
array(5) {
  [0]=>
  string(6) "header"
  ["url"]=>
  string(44) "https://mymauticurl.com/form/submit?formId=2"
  ["data"]=>
  array(1) {
    ["mauticform"]=>
    array(19) {
      ["first_name"]=>
      string(6) "first_name"
      ["last_name"]=>
      string(0) ""
      ["email"]=>
      string(21) "email"
      ["phone"]=>
      string(8) "phone"
      ["country"]=>
      string(2) "XX"
      ["city"]=>
      string(0) ""
      ["status"]=>
      string(6) "active"
      ["company"]=>
      NULL
      ["domain"]=>
      string(15) "custom property"
      ["skype"]=>
      string(0) ""
      ["submit"]=>
      NULL
      ["formId"]=>
      int(2)
      ["return"]=>
      string(0) ""
    }
  }
  ["header"]=>
  array(1) {
    [0]=>
    string(28) "X-Forwarded-For: xx.yy.zz.xx"	// NOTE: Correct IP in this header
  }
  ["query"]=>
  string(562) "Some query string here"
}
```

But still mautic is taking the IP of the server from where request is originating ( I have verified this )
Could it be that Mautic requires IP in some header other than X-Forwarded-For?

**Comment by escopecz** [comment]
Interesting. This must have change in Mautic. Create new issue in the https://github.com/mautic/mautic repository please. We cannot fix it from this one.

**Comment by escopecz** [comment]
Can you try it out and send a pull request with the change if that's true?
