### ISSUE TITLE
PHP error Undefined offset: 1 in MauticFormSubmit\Mautic\Form.php on line 65

### ISSUE THREAD

**Issue by steinjo** [escopecz/mautic-form-submit#6]
Hi,
just installed your script.  
1st:  thanks a bunch, this is exactly what I was looking for
2nd:  above mentioned error occurs, no data is transmitted to mautic, mautic error log is empty

Below is the returned array from $form->submit.

Potential reasons outside of your code:
- Does the code require PHP 7+ or only PHPSTAN as mentioned by you?  (I installed manually and have PHP5.6.36 running)
- Is there anything to be set in mautic configuration? (API is deactivated, identification by IP/tracking URL/device fingerprint is off) 
- Does the form in mautic require any special setting? (stay in form after submit action etc.?)
- I am testing from my development environment on localhost
- field primary_ip in return-array from $form->submit contains an IP-address related to the hosting provider where mautic is running, but this is not the IP address of my mautic installation.

Thanks in advance for your help.  Below follows the array returned by $form->submit
Joerg

array(4) {
  ["original_cookie"]=>
  array(4) {
    ["we-love-cookies"]=>
    string(1) "1"
    ["mautic_focus_1"]=>
    string(10) "1535438253"
    ["mautic_focus_2"]=>
    string(10) "1535438253"
    ["PHPSESSID"]=>
    string(26) "ka9otdk1lk749KJ64deaup8mu1"
  }
  ["new_cookie"]=>
  array(4) {
    ["blablabla"]=>
    string(1) "1"
    ["mautic_focus_1"]=>
    string(10) "1535438253"
    ["mautic_focus_2"]=>
    string(10) "1535438253"
    ["PHPSESSID"]=>
    string(26) "ka9otdk1lk749KJ64deaup8mu1"
  }
  ["request"]=>
  array(6) {
    [0]=>
    string(6) "header"
    ["url"]=>
    string(46) "https://mauticdomain.de/form/submit?formId=3"
    ["data"]=>
    array(1) {
      ["mauticform"]=>
      array(3) {
        ["email"]=>
        string(22) "email@address.de"
        ["formId"]=>
        int(3)
        ["return"]=>
        string(0) ""
      }
    }
    ["header"]=>
    array(2) {
      [0]=>
      string(20) "X-Forwarded-For: ::1"
      [1]=>
      string(14) "Client-Ip: ::1"
    }
    ["referer"]=>
    string(28) "http://localhost/index/index"
    ["query"]=>
    string(95) "mauticform%5Bemail%5D=email%40address.de&mauticform%5BformId%5D=3&mauticform%5Breturn%5D="
  }
  ["response"]=>
  array(3) {
    ["header"]=>
    string(0) ""
    ["content"]=>
    string(0) ""
    ["info"]=>
    array(26) {
      ["url"]=>
      string(46) "https://mauticdomain.de/form/submit?formId=3"
      ["content_type"]=>
      NULL
      ["http_code"]=>
      int(0)
      ["header_size"]=>
      int(0)
      ["request_size"]=>
      int(0)
      ["filetime"]=>
      int(-1)
      ["ssl_verify_result"]=>
      int(1)
      ["redirect_count"]=>
      int(0)
      ["total_time"]=>
      float(7.25)
      ["namelookup_time"]=>
      float(0.016)
      ["connect_time"]=>
      float(0.032)
      ["pretransfer_time"]=>
      float(0)
      ["size_upload"]=>
      float(0)
      ["size_download"]=>
      float(0)
      ["speed_download"]=>
      float(0)
      ["speed_upload"]=>
      float(0)
      ["download_content_length"]=>
      float(-1)
      ["upload_content_length"]=>
      float(-1)
      ["starttransfer_time"]=>
      float(0)
      ["redirect_time"]=>
      float(0)
      ["redirect_url"]=>
      string(0) ""
      ["primary_ip"]=>
      string(13) "IP-ADDRESS-OF-HOSTER-OF-MAUTIC"
      ["certinfo"]=>
      array(0) {
      }
      ["primary_port"]=>
      int(443)
      ["local_ip"]=>
      string(13) "AAA.BBB.CCC.DDD"
      ["local_port"]=>
      int(61119)
    }
  }
}

**Comment by escopecz** [comment]
Are you running the latest code? There is nothing on line 65: https://github.com/escopecz/mautic-form-submit/blob/master/src/Mautic/Form.php#L65

**Comment by steinjo** [comment]
Sorry, in your code its line 78:

list($header, $content) = explode("\r\n\r\n", curl_exec($ch), 2);

**Comment by escopecz** [comment]
Why is your code different? It's hard to advise if you have changes that I don't see.

**Comment by steinjo** [comment]
Hi John,
your code is completely unchanged.  Only the first lines (namespace and use) have been modified and (for whatever reasons) all spaces were removed when I copied it from github.  I copied the code last Friday.
Thanks Joerg

**Comment by escopecz** [comment]
Alright. Try to learn how to use Composer. It really pays off. 

Anyway, let's debug what's going on. Could you place `var_dump(curl_exec($ch));die;` and see what it returns?

**Comment by steinjo** [comment]
sorry for the delay and  ... will do :-)

I placed var_dump(curl_exec($ch));die; right before the line, where the error occurs (your line 78) and it returns:

bool(false)

**Comment by escopecz** [comment]
Hmm, it's erroring out. What will this return? Place it after the line with `curl_exec`? 

`var_dump(curl_error($ch));die;`

**Comment by steinjo** [comment]
ok, having your line (i added <pre> for better readability) directly after line 78 

> list($header, $content) = explode("\r\n\r\n", curl_exec($ch), 2);

produces the following (first line is the already mentioned error):
Notice: Undefined offset: 1 in X:\Office (oc)\IT_Computer\Programme\PHP\Projekte\digaserv\Aktuell\Code\Mvc\Library\MauticFormSubmit\Mautic\Form.php on line 65
string(63) "SSL certificate problem: unable to get local issuer certificate"

**Comment by escopecz** [comment]
Cool! So fix the SSL certificate on the domain where your Mautic instance lives and you should be OK, right?

For the next versions of this library we have to improve the error messages so debugging it wouldn't take so long.

**Comment by steinjo** [comment]
yep, correct in theory.  The issue is that the certificate is up and running like a charm.  It's verified by Let's Encrypt Authority and has passed all tests (ssl-trust.com etc.).
I call your method with 

> $mautic = new Mautic('https://mautic-domain.de');

So, I am a bit clueless what else to do with this.

**Comment by escopecz** [comment]
There must be some misconfiguration as CURL returns this error. Try to look around https://www.google.com/search?q=php+curl+%22SSL+certificate+problem%3A+unable+to+get+local+issuer+certificate%22&rlz=1C5CHFA_enCZ727CZ727&oq=php+curl+%22SSL+certificate+problem%3A+unable+to+get+local+issuer+certificate%22&aqs=chrome..69i57j69i64l3.3394j0j7&sourceid=chrome&ie=UTF-8

**Comment by steinjo** [comment]
Hehehehe, you know what it was?  The SSL-certificate on the mautic-server was perfectly all-right.  My development evironment, however, is based on XAMPP and that comes w/o a list of certificate issuers.  
After downloading it from here curl.haxx.se/ca/cacert.pem and installing it manually, your script works perfectly!
Thanks again for your help!

**Comment by escopecz** [comment]
Thanks for sharing the solution!
