### ISSUE TITLE
Cookies aren't set

### ISSUE THREAD

**Issue by pieterjanmaes** [escopecz/mautic-form-submit#7]
Hi, 

I used this composer script. De forms are correctly passed to Mautic, but there's a problem with the sending of cookies. That doesn't work and don't see any errors.

Do I need to configure something somewhere extra?  
CURL is active on the webserver, do I need other modules active?

Kind regards,

**Comment by escopecz** [comment]
Can you make sure that you're using the latest code? Because I was fixing that bit lately.

**Comment by pieterjanmaes** [comment]
I installed the latest code, downloaded via composer last week.

**Comment by escopecz** [comment]
Do you have Mautic JS tracking on the website that submits the form?

**Comment by pieterjanmaes** [comment]
I have the following Mautic JS included on every page:

`<script>
            (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
                w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
                m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://mywebsite.mautic.net/mtc.js','mt');
            mt('send', 'pageview');
        </script>`

**Comment by escopecz** [comment]
Please check if new version 1.1.3 that contains https://github.com/escopecz/mautic-form-submit/pull/9 fixes your issue. If not let us know and I will reopen.
