### ISSUE TITLE
Contacts not merged

### ISSUE THREAD

**Issue by steinjo** [escopecz/mautic-form-submit#8]
After bringing your cript successfully to work (see closed issue #6) , I noticed that mautic creates duplicate contacts and does not merge them.  After analysing the cookie-settings by your script, this could be a possible root cause.  

This is what I did to produce the findings:
1. Deleted all cookies related to my website in firefox for a clean start
2. Calling a page on my website leads to a correct creation of anonymous contact in mautic with ID 475
3. Login into my webspace => your script, which is called from the login-action of my website, runs correctly and sends email-address and user id of my website (website_id) to mautic into identified mautic-contact with ID 397 (this contact existed previously with custom-field website_id being field with unique identifier, existing fields email and company_email in mautic are unique identifiers as well)
==>> Question 1:  shouldn't contact 475 be merged with contact 397?
4. Calling another page of my website immediately afterwards shows that page call under anonymous mautic contact 475 and not under contact 397
==>> Question 2:  why is that page call not shown unter identified contact 397?

When analysing the cookies after above step 4, I realize that they are set in paths /index/ and /user/ as follows:
![image](https://user-images.githubusercontent.com/8441009/43690041-ed2a9774-9903-11e8-80c0-493cf295b4ab.png)

Could it be that mautic takes the cookies from path /user/ (which contains the anonymous contact with ID 475), so the cookie, which your script aparently writes into path /index/ and which contains the identified user 397 is ignored?  This would also fit to the observation leading to above question #1.  The cookies after step 2 were as follows:
![image](https://user-images.githubusercontent.com/8441009/43690165-ad551eba-9905-11e8-8007-74ae7dc51b37.png)

**Comment by escopecz** [comment]
Maybe related to https://github.com/mautic/mautic/pull/6045?

I can't find any way how to set the cookie path via CURL. Can you?

**Comment by steinjo** [comment]
That could very well be.  What do you recommend?  Change line 113 in app/bundles/CoreBundle/EventListener/BuildJsSubscriber.php to  path=/" at the end and then test it on my installation?

**Comment by escopecz** [comment]
Sure, give it a go and let us know.

**Comment by steinjo** [comment]
Done, here are the findings:

1. changed line 113 in app/bundles/CoreBundle/EventListener/BuildJsSubscriber.php
From:  document.cookie = name+"="+value+";";
To:  document.cookie = name+"="+value+"; path=/";

Not logged in, calling any page of my application:
- Cookies are all set in path "/" (as expected)
![image](https://user-images.githubusercontent.com/8441009/43718849-3f7f6544-998c-11e8-93d0-3581a8caa1bc.png)
- mautic creates an anonymous contact with ID 489  (as expected)

Login into application, executing your script
- cookies are set in "mixed" paths, I assume the one in path /user/ come from your script:
![image](https://user-images.githubusercontent.com/8441009/43718903-7355f3f6-998c-11e8-8e7e-6607e936e452.png)
- mautic tracks submitted login-form in existing identified contact 397 (as expected - this is the one containing the email adress that is also used at login)
- mautic creates another contact with ID 490 with page URL = the one after login
Problem:  why is existing anonymous contact 489 not used?  Why is contact 490 not merged with existing identified contact 397?

Clicking on another page, still being logged in:
- Cookies:  similar to above:
![image](https://user-images.githubusercontent.com/8441009/43719241-7dea59fa-998d-11e8-8871-5102e2a2c155.png)
- mautic contact 397 remains untouched
- page hit on another page is tracked in contact 490
Problem:  why not tracked in contact 397

Result:  the problem remains largely unchanged

2. I then additionally changed line 64 in your script MauticFormSubmit/Cookie.php
From:  return setcookie($key, $value);
To:  return setcookie($key, $value, 0, '/');
in order to force also your script to set cookies only in path /

The results are largely unchanged, here are the details:

When clicking on any page being logged out, mautic still creates 2 contacts (492 and 493, counting the page hit in 493)

When loggin in, the resulting page hit is still counted in contact 493 and not in identified contact 397 (as it should).  Cookies look a bit different after login (less cookies and all in path /, as expected):
![image](https://user-images.githubusercontent.com/8441009/43719616-77e3add0-998e-11e8-8366-cf8f79efbe53.png)

So, back to the drawing board, I guess ...

**Comment by escopecz** [comment]
I think it is the problem that https://github.com/mautic/mautic/pull/6045 is solving. It had been merged to core now and should be released in 2 weeks. Let us know if the problem persists after that. I will reopen.

**Comment by steinjo** [comment]
Thanks!  Has it been released yet?  In ZIP-file from https://github.com/mautic/mautic, most up-to-date file date is still at 25Mar19.

**Comment by escopecz** [comment]
You can see on that PR that it belongs to milestone 2.15.2. Latest release is 2.15.1. That means it hasn't been released yet but it's coming.
